export const createEmptyTemplate = () => ({
  _id: "",
  name: "New Template",
  width: 360,
  height: 540,
  backgroundColor: "#ffffff",
  backgroundImage: "",
  overlayColor: "#000000",
  overlayOpacity: 0,
  elements: [],
});

const createId = (type) => `${type}_${Date.now()}_${Math.floor(Math.random() * 100000)}`;

export const createElement = (type) => {
  const id = createId(type);
  const common = {
    id,
    type,
    label: type.toUpperCase(),
    x: 20,
    y: 20,
    width: 140,
    height: 36,
    fontSize: 16,
    fontFamily: "Arial",
    fontWeight: "normal",
    align: "left",
    color: "#111827",
    backgroundColor: "transparent",
    borderRadius: 0,
    stroke: "#94a3b8",
    strokeWidth: 1,
    opacity: 1,
    shapeKind: "rect",
    curveDepth: 16,
    text: "",
    fieldKey: "",
    qrValueKey: "rollNumber",
  };

  if (type === "text") {
    return {
      ...common,
      label: "Static Text",
      text: "COLLEGE NAME",
      width: 240,
      height: 40,
      fontSize: 24,
      fontWeight: "bold",
    };
  }

  if (type === "field") {
    return {
      ...common,
      label: "Student Field",
      text: "",
      fieldKey: "fullName",
      width: 220,
      fontSize: 18,
    };
  }

  if (type === "photo") {
    return {
      ...common,
      label: "Photo",
      fieldKey: "photoUrl",
      photoShape: "rect",
      width: 100,
      height: 120,
      color: "#334155",
      backgroundColor: "#e2e8f0",
    };
  }

  if (type === "shape") {
    return {
      ...common,
      label: "Design Shape",
      width: 140,
      height: 80,
      color: "#0f172a",
      backgroundColor: "#cbd5e1",
      borderRadius: 16,
      stroke: "#cbd5e1",
      strokeWidth: 0,
      opacity: 0.95,
      shapeKind: "curveTop",
      curveDepth: 22,
    };
  }

  return {
    ...common,
    label: "QR Code",
    qrValueKey: "rollNumber",
    width: 90,
    height: 90,
    color: "#111827",
    backgroundColor: "#ffffff",
  };
};

const baseElement = (type, patch = {}) => ({
  id: createId(type),
  type,
  label: patch.label || type.toUpperCase(),
  text: "",
  fieldKey: "",
  qrValueKey: "rollNumber",
  x: 20,
  y: 20,
  width: 120,
  height: 40,
  fontSize: 16,
  fontFamily: "Arial",
  fontWeight: "normal",
  align: "left",
  color: "#111827",
  backgroundColor: "transparent",
  borderRadius: 0,
  stroke: "#94a3b8",
  strokeWidth: 1,
  opacity: 1,
  shapeKind: "rect",
  curveDepth: 16,
  ...patch,
});

const textEl = (patch) => baseElement("text", patch);
const fieldEl = (patch) => baseElement("field", patch);
const photoEl = (patch) => baseElement("photo", patch);
const qrEl = (patch) => baseElement("qr", patch);

const classicVerticalBlue = () => ({
  _id: "",
  name: "Classic Vertical Blue",
  width: 360,
  height: 540,
  backgroundColor: "#f8fafc",
  backgroundImage: "",
  elements: [
    textEl({
      label: "College Name",
      text: "ZENITH COLLEGE OF ENGINEERING",
      x: 24,
      y: 24,
      width: 312,
      height: 34,
      fontSize: 15,
      fontWeight: "bold",
      align: "center",
      color: "#0f172a",
    }),
    textEl({
      label: "Card Title",
      text: "STUDENT ID CARD",
      x: 24,
      y: 58,
      width: 312,
      height: 28,
      fontSize: 14,
      fontWeight: "bold",
      align: "center",
      color: "#1d4ed8",
    }),
    photoEl({
      label: "Student Photo",
      fieldKey: "photoUrl",
      x: 24,
      y: 110,
      width: 110,
      height: 132,
      backgroundColor: "#e2e8f0",
      stroke: "#475569",
      strokeWidth: 1,
    }),
    textEl({
      text: "Name:",
      x: 150,
      y: 118,
      width: 64,
      height: 26,
      fontSize: 14,
      fontWeight: "bold",
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "fullName",
      x: 214,
      y: 118,
      width: 122,
      height: 26,
      fontSize: 14,
      fontWeight: "bold",
      color: "#0f172a",
    }),
    textEl({
      text: "Roll No:",
      x: 150,
      y: 150,
      width: 64,
      height: 24,
      fontSize: 13,
      fontWeight: "bold",
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "rollNumber",
      x: 214,
      y: 150,
      width: 122,
      height: 24,
      fontSize: 13,
      color: "#0f172a",
    }),
    textEl({
      text: "Department:",
      x: 150,
      y: 178,
      width: 84,
      height: 24,
      fontSize: 13,
      fontWeight: "bold",
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "department",
      x: 234,
      y: 178,
      width: 102,
      height: 24,
      fontSize: 13,
      color: "#0f172a",
    }),
    textEl({
      text: "Course:",
      x: 150,
      y: 206,
      width: 60,
      height: 24,
      fontSize: 13,
      fontWeight: "bold",
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "course",
      x: 214,
      y: 206,
      width: 122,
      height: 24,
      fontSize: 13,
      color: "#0f172a",
    }),
    qrEl({
      label: "QR",
      qrValueKey: "rollNumber",
      x: 24,
      y: 266,
      width: 96,
      height: 96,
      backgroundColor: "#ffffff",
      stroke: "#1e293b",
      strokeWidth: 1,
    }),
    textEl({
      text: "Year:",
      x: 150,
      y: 272,
      width: 40,
      height: 24,
      fontSize: 13,
      fontWeight: "bold",
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "year",
      x: 194,
      y: 272,
      width: 142,
      height: 24,
      fontSize: 13,
      color: "#0f172a",
    }),
    textEl({
      text: "Phone:",
      x: 150,
      y: 300,
      width: 52,
      height: 24,
      fontSize: 13,
      fontWeight: "bold",
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "phone",
      x: 204,
      y: 300,
      width: 132,
      height: 24,
      fontSize: 13,
      color: "#0f172a",
    }),
    textEl({
      text: "Valid Till: 31-05-2027",
      x: 24,
      y: 384,
      width: 312,
      height: 24,
      fontSize: 12,
      align: "center",
      color: "#334155",
    }),
    textEl({
      text: "Authorized Signature",
      x: 192,
      y: 478,
      width: 144,
      height: 24,
      fontSize: 12,
      align: "center",
      color: "#334155",
    }),
  ],
});

const modernHorizontalDark = () => ({
  _id: "",
  name: "Modern Horizontal Dark",
  width: 540,
  height: 320,
  backgroundColor: "#0f172a",
  backgroundImage: "",
  elements: [
    textEl({
      text: "STUDENT ACCESS CARD",
      x: 20,
      y: 20,
      width: 500,
      height: 28,
      fontSize: 14,
      align: "left",
      color: "#38bdf8",
      fontWeight: "bold",
    }),
    textEl({
      text: "ZYNTRA UNIVERSITY",
      x: 20,
      y: 44,
      width: 500,
      height: 32,
      fontSize: 20,
      fontWeight: "bold",
      color: "#f8fafc",
    }),
    photoEl({
      fieldKey: "photoUrl",
      x: 24,
      y: 90,
      width: 115,
      height: 145,
      backgroundColor: "#1e293b",
      stroke: "#38bdf8",
      strokeWidth: 1,
    }),
    fieldEl({
      fieldKey: "fullName",
      x: 158,
      y: 92,
      width: 292,
      height: 30,
      fontSize: 23,
      fontWeight: "bold",
      color: "#ffffff",
    }),
    textEl({
      text: "Roll:",
      x: 158,
      y: 130,
      width: 48,
      height: 24,
      fontSize: 13,
      color: "#94a3b8",
    }),
    fieldEl({
      fieldKey: "rollNumber",
      x: 206,
      y: 130,
      width: 146,
      height: 24,
      fontSize: 13,
      color: "#ffffff",
    }),
    textEl({
      text: "Department:",
      x: 158,
      y: 157,
      width: 88,
      height: 24,
      fontSize: 13,
      color: "#94a3b8",
    }),
    fieldEl({
      fieldKey: "department",
      x: 246,
      y: 157,
      width: 206,
      height: 24,
      fontSize: 13,
      color: "#ffffff",
    }),
    textEl({
      text: "Course:",
      x: 158,
      y: 184,
      width: 60,
      height: 24,
      fontSize: 13,
      color: "#94a3b8",
    }),
    fieldEl({
      fieldKey: "course",
      x: 218,
      y: 184,
      width: 232,
      height: 24,
      fontSize: 13,
      color: "#ffffff",
    }),
    textEl({
      text: "Year:",
      x: 158,
      y: 211,
      width: 38,
      height: 24,
      fontSize: 13,
      color: "#94a3b8",
    }),
    fieldEl({
      fieldKey: "year",
      x: 196,
      y: 211,
      width: 68,
      height: 24,
      fontSize: 13,
      color: "#ffffff",
    }),
    qrEl({
      qrValueKey: "rollNumber",
      x: 452,
      y: 90,
      width: 72,
      height: 72,
      backgroundColor: "#ffffff",
      stroke: "#38bdf8",
      strokeWidth: 1,
    }),
    textEl({
      text: "Scan for verification",
      x: 432,
      y: 168,
      width: 100,
      height: 24,
      fontSize: 9,
      align: "center",
      color: "#94a3b8",
    }),
    textEl({
      text: "Emergency: +91-99999-99999",
      x: 20,
      y: 280,
      width: 500,
      height: 20,
      fontSize: 10,
      color: "#94a3b8",
      align: "left",
    }),
  ],
});

const minimalClean = () => ({
  _id: "",
  name: "Minimal Clean White",
  width: 360,
  height: 540,
  backgroundColor: "#ffffff",
  backgroundImage: "",
  elements: [
    textEl({
      text: "CAMPUS ID",
      x: 24,
      y: 26,
      width: 312,
      height: 26,
      fontSize: 12,
      fontWeight: "bold",
      align: "center",
      color: "#6b7280",
    }),
    photoEl({
      fieldKey: "photoUrl",
      x: 115,
      y: 64,
      width: 130,
      height: 150,
      backgroundColor: "#f1f5f9",
      stroke: "#cbd5e1",
      strokeWidth: 1,
    }),
    fieldEl({
      fieldKey: "fullName",
      x: 40,
      y: 230,
      width: 280,
      height: 34,
      fontSize: 24,
      fontWeight: "bold",
      align: "center",
      color: "#111827",
    }),
    fieldEl({
      fieldKey: "department",
      x: 40,
      y: 266,
      width: 280,
      height: 24,
      fontSize: 14,
      align: "center",
      color: "#374151",
    }),
    textEl({
      text: "Roll Number",
      x: 40,
      y: 306,
      width: 280,
      height: 20,
      fontSize: 11,
      align: "center",
      color: "#9ca3af",
    }),
    fieldEl({
      fieldKey: "rollNumber",
      x: 40,
      y: 326,
      width: 280,
      height: 24,
      fontSize: 18,
      fontWeight: "bold",
      align: "center",
      color: "#111827",
    }),
    fieldEl({
      fieldKey: "course",
      x: 40,
      y: 364,
      width: 280,
      height: 24,
      fontSize: 13,
      align: "center",
      color: "#4b5563",
    }),
    textEl({
      text: "Academic Year",
      x: 40,
      y: 406,
      width: 140,
      height: 20,
      fontSize: 11,
      align: "center",
      color: "#9ca3af",
    }),
    fieldEl({
      fieldKey: "year",
      x: 40,
      y: 424,
      width: 140,
      height: 20,
      fontSize: 14,
      align: "center",
      color: "#111827",
    }),
    qrEl({
      qrValueKey: "rollNumber",
      x: 228,
      y: 392,
      width: 90,
      height: 90,
      backgroundColor: "#ffffff",
      stroke: "#d1d5db",
      strokeWidth: 1,
    }),
  ],
});

const vibrantCampus = () => ({
  _id: "",
  name: "Vibrant Campus Card",
  width: 360,
  height: 540,
  backgroundColor: "#ecfeff",
  backgroundImage: "",
  elements: [
    textEl({
      text: "CAMPUS CONNECT",
      x: 18,
      y: 18,
      width: 324,
      height: 28,
      fontSize: 13,
      fontWeight: "bold",
      align: "center",
      color: "#0f766e",
    }),
    textEl({
      text: "STUDENT IDENTITY PASS",
      x: 18,
      y: 42,
      width: 324,
      height: 28,
      fontSize: 16,
      fontWeight: "bold",
      align: "center",
      color: "#0f172a",
    }),
    photoEl({
      fieldKey: "photoUrl",
      x: 30,
      y: 92,
      width: 120,
      height: 138,
      backgroundColor: "#cffafe",
      stroke: "#0d9488",
      strokeWidth: 1,
    }),
    fieldEl({
      fieldKey: "fullName",
      x: 164,
      y: 104,
      width: 166,
      height: 30,
      fontSize: 20,
      fontWeight: "bold",
      color: "#0f172a",
    }),
    fieldEl({
      fieldKey: "rollNumber",
      x: 164,
      y: 138,
      width: 166,
      height: 24,
      fontSize: 13,
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "department",
      x: 164,
      y: 164,
      width: 166,
      height: 24,
      fontSize: 13,
      color: "#334155",
    }),
    fieldEl({
      fieldKey: "course",
      x: 30,
      y: 250,
      width: 300,
      height: 26,
      fontSize: 14,
      fontWeight: "bold",
      align: "center",
      color: "#115e59",
    }),
    textEl({
      text: "CONTACT",
      x: 30,
      y: 292,
      width: 88,
      height: 22,
      fontSize: 11,
      fontWeight: "bold",
      color: "#0f766e",
    }),
    fieldEl({
      fieldKey: "phone",
      x: 30,
      y: 314,
      width: 180,
      height: 22,
      fontSize: 13,
      color: "#0f172a",
    }),
    textEl({
      text: "EMAIL",
      x: 30,
      y: 346,
      width: 88,
      height: 22,
      fontSize: 11,
      fontWeight: "bold",
      color: "#0f766e",
    }),
    fieldEl({
      fieldKey: "email",
      x: 30,
      y: 368,
      width: 300,
      height: 24,
      fontSize: 11,
      color: "#0f172a",
    }),
    qrEl({
      qrValueKey: "rollNumber",
      x: 236,
      y: 284,
      width: 94,
      height: 94,
      backgroundColor: "#ffffff",
      stroke: "#14b8a6",
      strokeWidth: 1,
    }),
    textEl({
      text: "Carry this card while on campus.",
      x: 30,
      y: 490,
      width: 300,
      height: 20,
      fontSize: 10,
      align: "center",
      color: "#0f766e",
    }),
  ],
});

export const AVAILABLE_FIELD_KEYS = [
  { value: "fullName", label: "Full Name" },
  { value: "rollNumber", label: "Roll Number" },
  { value: "department", label: "Department" },
  { value: "course", label: "Course" },
  { value: "year", label: "Year" },
  { value: "email", label: "Email" },
  { value: "phone", label: "Phone" },
  { value: "photoUrl", label: "Photo URL" },
];

export const getPredefinedTemplates = () => [
  classicVerticalBlue(),
  modernHorizontalDark(),
  minimalClean(),
  vibrantCampus(),
];
